### ISSUE TITLE
Allow users to create session proposals

### ISSUE THREAD

**Issue by dasjo** [AmazeeLabs/drupalmountaincamp_ch#11]

**Comment by dasjo** [comment]
Fields are defined here:
https://docs.google.com/spreadsheets/d/1JD3v6u3xsJXlm8Gq_4--jhYifjgc2wkZHBvnukCgwZM/edit#gid=1430880655

Session creation is ready for testing:
http://drupalmountaincamp.ch.dev.zh1.compact.amazee.io/node/add/session

**Comment by Schnitzel** [comment]
Tested with a user that I created myself as admin.
Feedback:
- I'm not sure what the _Downloads_ Field is for
- There is an Revisions Block that is confusing, could probably be hidden
- The Description has a summary settings, I don't think that is necessary

**Comment by dasjo** [comment]
thx a lot!

worked on your feedback:
- downloads field has been renamed to "slides upload"
- revisions are disabled for sessions
- description summary is removed
- level of expertise set to required
- preview is disabled

display
- title issue, see #12
- taxonomy terms are not linked anymore
- url aliases are now generated via pathauto

**Comment by Schnitzel** [comment]
as discussed in Prague, we will go full on MVP:
- No user registration necessary for session submission (just for anonymous users)
- No preview, display or edit of sessions after submitting (for now, can be added later)
- No display of submitted sessions for now

**Comment by dasjo** [comment]
working on this now

**Comment by dasjo** [comment]
The feedback & MVP has been implemented on dev & live:
https://drupalmountaincamp.ch/node/add/session
drupalmountaincamp.ch.dev.zh1.compact.amazee.io/node/add/session

**Comment by dan2k3k4** [comment]
Tested and works on prod.

- Redirected after submission
- The view on dev: no longer has taxonomy links
- Url alias is generated correctly on dev view

**Comment by dasjo** [comment]
thanks, moved to done
