### ISSUE TITLE
WYSIWYG improvements

### ISSUE THREAD

**Issue by dasjo** [AmazeeLabs/drupalmountaincamp_ch#34]

**Comment by dasjo** [comment]
AC
- Bullet points have proper margin-left (currently they are positioned to the outside left of the text block)
- Paragraphs <p> have proper vertical margin

test urls
https://drupalmountaincamp.ch/sessions/drupal-8-initiatives
https://drupalmountaincamp.ch/node/add/session

**Comment by pheadeaux** [comment]
there are also config updates. so make sure to switch the session view to show content
