### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Schnitzel** [AmazeeLabs/drupalmountaincamp_ch#4]
As an organiser I would like people to register for the event so that I can do the event

AC:
- Registration is a separate page
- Registration will happen with Eventbrite within an iFrame on that Registration Page

**Comment by Schnitzel** [comment]
this is the iframe code:

```
<div style="width:100%; text-align:left;"><iframe src="//eventbrite.com/tickets-external?eid=29407244861&ref=etckt" frameborder="0" height="275" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe><div style="font-family:Helvetica, Arial; font-size:12px; padding:10px 0 5px; margin:2px; width:100%; text-align:left;" ><a class="powered-by-eb" style="color: #ADB0B6; text-decoration: none;" target="_blank" href="http://www.eventbrite.com/">Powered by Eventbrite</a></div></div>
```

**Comment by Schnitzel** [comment]
plus the colors can be adapted here: https://www.eventbrite.com/ticketwidget?eid=29407244861
find the passwords here: https://docs.google.com/document/d/1KhcHWQk-h2VImbce81Lty_Y-GJthzQ0je2KMq0zfkjQ/edit#

**Comment by Schnitzel** [comment]
Created https://drupalmountaincamp.ch/register?cache
the basic pages are a bit broken (don't show H1, plus they're lacking a margin top, will create new ticket).

But for now this should work, needs testing

**Comment by dasjo** [comment]
register process tested

on the eventbrite form
- title of the event brite page is "Drupal MountainCamp 2016" -> should always be "Drupal Mountain Camp 2016" with the space between mountain and camp. 
- address "Davos Platz, Switzerland" -> can this show Kongresszentrum Davos, Switzerland instead?
- organizer section has facebook, twitter -> add a link to the website here as well?

after signing up, on eventbrite
- when on eventbrite, i go to my account -> tickets, i'm seeing "upcoming event" with Drupal mountain camp (https://www.eventbrite.co.uk/u/147776019446/) -> the event image is very dark and unclear -> can we use a nicer one here?

will add more feedback later

**Comment by Schnitzel** [comment]
fixed:
- changed Title in eventbrite to "Drupal Mountain Camp 2016"
- Uploaded a better picture
- Added link to the website

can't fix:
- the address is set correctly (with Kongresszentrum Davos, 49a Talstrasse, 7270 Davos Platz, Switzerland) but unfortunately on the header evenbrite only shows "7270 Davos Platz, Switzerland"

**Comment by dasjo** [comment]
ok great, moving to done
