### ISSUE TITLE
Add node (or block on frontpage?) with rough timeline

### ISSUE THREAD

**Issue by JeromeZech** [AmazeeLabs/drupalmountaincamp_ch#43]
IMHO the program outline should be fine:

**Thursday**
- Summits
- Networking
- Sprints

**Friday**
- Sessions
- Sprints
- Workshops
- Official Party

**Saturday**
- Sessions (weekend day)
- Sprints
- Workshop
- Hockey HCD vs. ZSC

**Sunday**
- Outdoor Activities
- Tear-down
- Sprints

**Comment by Schnitzel** [comment]
it's on the frontpage now
