### ISSUE TITLE
Add hotel booking link on ticket buy page

### ISSUE THREAD

**Issue by ucola** [AmazeeLabs/drupalmountaincamp_ch#45]
would be nice if we can put a link or text on the ticket buy page for booking the hotels over our page. right now we have only a text on https://drupalmountaincamp.ch/davos "book your hotel"

**Comment by dan2k3k4** [comment]
I don't think I have the eventbrite access - @Schnitzel, are you able to add the link for hotel? Thanks in advance

**Comment by Schnitzel** [comment]
passwords are all here :) https://docs.google.com/document/d/1KhcHWQk-h2VImbce81Lty_Y-GJthzQ0je2KMq0zfkjQ/edit

**Comment by dan2k3k4** [comment]
Done & added this as text on confirmation page as well as email:

> Thanks for registering for Drupal Mountain Camp. Don't forget to book your stay!
> 
> Discounted options are available from CHF 67.00 per person/night, more info: http://www.davoscongress.ch/DrupalMountainCamp
> 
> If you are interested to book a holiday apartment for 3-6 people, please be aware that a minimum stay of 7 nights is required. For an offer please contact Davos Congress.
>
